# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: hello-api
#   namespace: argocd
#   labels:
#     app: hello-api
#     tier: frontend
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: hello-api
#   template:
#     metadata:
#       name: hello-api
#       labels:
#         app: hello-api
#     spec:
#       containers:
#         - name: hello-api
#           image: falace/api_python:deploy-${{github.sha}}
#           ports:
#             - containerPort: 8000


apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-api
  namespace: argocd
  labels:
    app: hello-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-api
  template:
    metadata:
      labels:
        app: hello-api
    spec:
      containers:
        - name: hello-api
          image: falace/api_python:deploy-${{github.sha}}
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20

---

apiVersion: v1
kind: Service
metadata:
  name: hello-api
  namespace: argocd
spec:
  type: NodePort
  selector:
    app: hello-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000 
      nodePort: 30080
